Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 3306, host: 3306, host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |vb|
		vb.name = "ubu18"
		vb.memory = 4096
  end

  config.vm.provision "shell", path: "provision.sh"
end
